version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000

  db:
    image: library/postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
